databases:
  - name: querykey-prod
    databaseName: querykey_prod
    user: querykey
    plan: starter

services:
  - type: web
    name: querykey-prod-web
    env: docker
    dockerfilePath: ./app/Dockerfile
    dockerContext: .
    plan: standard
    domains:
      - app.openpipe.ai
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: querykey-prod
          property: connectionString
      - fromGroup: querykey-prod
      - key: NEXT_PUBLIC_SOCKET_URL
        value: https://querykey-prod-wss.onrender.com
      # Render support says we need to manually set this because otherwise
      # sometimes it checks a different random port that NextJS opens for
      # liveness and the liveness check fails.
      - key: PORT
        value: 10000

  - type: web
    name: querykey-prod-wss
    env: docker
    dockerfilePath: ./app/Dockerfile
    dockerContext: .
    plan: free
    dockerCommand: pnpm tsx src/wss-server.ts
